name: nb_utils
description: This package helps you daily usable function and ready made Widgets with ease.
version: 4.4.10
#homepage: https://bhoominn.github.io
repository: https://github.com/bhoominn/nb_utils
issue_tracker: https://github.com/bhoominn/nb_utils/issues
publish_to: https://pub.dartlang.org

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.6
  fluttertoast: ^8.0.8
  connectivity_plus: ^2.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.nb.nb_utils
        pluginClass: NbUtilsPlugin
      ios:
        pluginClass: NbUtilsPlugin
      linux:
        pluginClass: nb_utils_plugin
      macos:
        pluginClass: NbUtilsPlugin
      windows:
        pluginClass: NbUtilsPlugin

  fonts:
    - family: LineAwesomeIcons
      fonts:
        - asset: fonts/LineAwesome.ttf
          weight: 400