name: explorer
description: Drive explorer, built with Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  win32:
    path: ../../

dev_dependencies:
  pedantic: ^1.9.0

publish_to: none
