name: firebase_core_example
description: Demonstrates how to use the firebase_core plugin.

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
    path: ../

dev_dependencies:
  e2e: ^0.6.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.1.0 <3.0.0"
