name: firebase_core_example
description: Demonstrates how to use the firebase_core plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_core:
    path: ../
  flutter:
    sdk: flutter

dependency_overrides:
  firebase_core_platform_interface:
    path: ../../firebase_core_platform_interface
  firebase_core_web:
    path: ../../firebase_core_web

dev_dependencies:
  e2e: ^0.6.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
