name: pedantic
version: 1.10.0-nullsafety.1
description: >-
  The Dart analyzer settings and best practices used internally at Google.
homepage: https://github.com/dart-lang/pedantic

environment:
  # This must remain a tight constraint until nnbd is stable
  sdk: '>=2.10.0-0 <2.11.0'
