name: connectivity_plus_example
description: Demonstrates how to use the connectivity_plus plugin.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.16.4
  pedantic: ^1.10.0

dependency_overrides:
  args: ^2.0.0

flutter:
  uses-material-design: true
