name: flutter_plugin_android_lifecycle_example
description: Demonstrates how to use the flutter_plugin_android_lifecycle plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    path: ../../integration_test

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

  flutter_plugin_android_lifecycle:
    path: ../

flutter:
  uses-material-design: true
