name: firebase_dynamic_links
description:
  Flutter plugin for Google Dynamic Links for Firebase, an app solution for creating
  and handling links across multiple platforms.
version: 3.0.1
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_dynamic_links
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_dynamic_links

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_core: ^1.10.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^6.0.2

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebasedynamiclinks
        pluginClass: FirebaseDynamicLinksPlugin
      ios:
        pluginClass: FLTFirebaseDynamicLinksPlugin
