# Use the analysis options settings from the top level of the repo (not
# the ones from above, which include the `public_member_api_docs` rule).

include: ../../analysis_options.yaml

linter:
  rules:
    avoid_catches_without_on_clauses: true
    curly_braces_in_flow_control_structures: true
    library_private_types_in_public_api: false # Tool does not have any public API
    prefer_relative_imports: true
    unawaited_futures: true
