name: node_io
description: Like dart:io but with Node.js.
version: 1.2.0
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  file: ^5.0.0
  node_interop: ^1.2.1
  path: ^1.6.2

dev_dependencies:
  js: ^0.6.0
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ">=1.10.0 <1.10.2"
  build_node_compilers: ^0.3.0
  build_test: ^1.0.0
