name: recase
version: 3.0.1
description: Changes the case of the input text to the desire case convention.
homepage: https://github.com/techniboogie-dart/recase
environment:
  sdk: '>=2.6.0 <3.0.0'
dev_dependencies:
  test: '^1.0.0'
