name: english_words
description: >
  Utilities for working with English words. Counts syllables, generates
  well-sounding word combinations, and provides access to the top 5000 English
  words by usage.
version: 3.1.5
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://github.com/filiph/english_words

environment:
  sdk: '>=1.22.0 <3.0.0'

dependencies:
  string_scanner: ^1.0.1

dev_dependencies:
  benchmark_harness: ^1.0.4
  test: ^1.0.0
