name: shared_preferences_macos
description: macOS implementation of the shared_preferences plugin.
repository: https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences_macos
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+shared_preferences%22
version: 2.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: shared_preferences
    platforms:
      macos:
        pluginClass: SharedPreferencesPlugin

dependencies:
  flutter:
    sdk: flutter
  shared_preferences_platform_interface: ^2.0.0

dev_dependencies:
  pedantic: ^1.10.0
