name: firebase_core_web
description: The web implementation of firebase_core
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core/firebase_core_web
version: 0.2.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseCoreWeb
        fileName: firebase_core_web.dart

dependencies:
  firebase: ^7.3.0
  firebase_core_platform_interface: ^2.0.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.8
  js: ^0.6.1+1

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  firebase_core: ^0.5.0

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
