name: cloud_firestore
description:
  Flutter plugin for Cloud Firestore, a cloud-hosted, noSQL database with
  live synchronization and offline support on Android and iOS.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore
version: 0.14.0+2

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.firestore
        pluginClass: FlutterFirebaseFirestorePlugin
      ios:
        pluginClass: FLTFirebaseFirestorePlugin
      macos:
        pluginClass: FLTFirebaseFirestorePlugin
      web:
        default_package: cloud_firestore_web

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  quiver: ">=2.0.0 <3.0.0"
  firebase_core: ">=0.5.0 <0.6.0"
  firebase_core_platform_interface: ">=2.0.0 <2.1.0"
  cloud_firestore_platform_interface: ">=2.0.1 <2.1.0"
  cloud_firestore_web: ">=0.2.0+1 <0.3.0"

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: ^1.8.0

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
