name: xml
version: 5.3.1

description: A lightweight library for parsing, traversing, querying, transforming and building XML documents.
homepage: https://github.com/renggli/dart-xml

environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  collection: ^1.15.0
  meta: ^1.7.0
  petitparser: ^4.3.0
dev_dependencies:
  args: ^2.2.0
  lints: ^1.0.0
  test: ^1.17.0
