name: term_glyph
version: 1.2.0

description: Useful Unicode glyphs and ASCII substitutes.
homepage: https://github.com/dart-lang/term_glyph

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  csv: '>=3.0.0 <5.0.0'
  dart_style: '>=0.2.0 <2.0.0'
  meta: ^1.3.0-nullsafety
  test: ^1.16.0-nullsafety
