name: persistent_bottom_nav_bar_example_project
description: An example project for persistent_bottom_nav_bar

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

