name: firebase_core_web
description: The web implementation of firebase_core
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core/firebase_core_web
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core/firebase_core_web
version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  firebase_core_platform_interface: ^4.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  meta: ^1.3.0

dev_dependencies:
  firebase_core: ^1.2.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseCoreWeb
        fileName: firebase_core_web.dart
