name: e2e
description: Runs tests that use the flutter_test API as integration tests.
version: 0.6.0
homepage: https://github.com/flutter/plugins/tree/master/packages/e2e

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.flutter.plugins.e2e
        pluginClass: E2EPlugin
      ios:
        pluginClass: E2EPlugin
