name: firebase_auth_platform_interface
description: A common platform interface for the firebase_auth plugin.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth_platform_interface
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 6.1.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.5"

dependencies:
  firebase_core: ^1.8.0
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  firebase_core_platform_interface: ^4.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
