name: firebase
description: Firebase libraries for Dart on the web and server
version: 7.3.0
homepage: https://github.com/FirebaseExtended/firebase-dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: '>=0.11.3 <0.13.0'
  http_parser: ^3.0.0
  js: ^0.6.0

dev_dependencies:
  googleapis_auth: ^0.2.3+5
  path: ^1.3.9
  pedantic: ^1.3.0
  test: ^1.6.0
  service_worker: ^0.2.0

  build_runner: ^1.0.0
  build_test: ^1.0.0
  build_web_compilers: '>=1.2.0 <3.0.0'
