name: syncfusion_flutter_core
description: Syncfusion Flutter Core is a dependent package for all the Syncfusion Flutter widgets. 
version: 18.2.55
homepage: https://github.com/syncfusion/flutter-examples

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  utf: ^0.9.0+5
  url_launcher: ">=5.1.3 <5.6.1"
  pedantic: ">=1.9.0 <1.9.9"

flutter:
