name: alt_http
version: 0.3.0
description: Patched original Dart HttpClient to allow case sensitive headers.
homepage: https://github.com/shaxxx/AltHttp

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.10.0
