name: sqlite3
description: Provides lightweight yet convenient bindings to SQLite by using dart:ffi
version: 1.1.2
homepage: https://github.com/simolus3/sqlite3.dart/tree/master/sqlite3
issue_tracker: https://github.com/simolus3/sqlite3.dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  ffi: ^1.0.0
  meta: ^1.3.0

dev_dependencies:
  build_ffi_generator:
    hosted:
      url: https://simonbinder.eu
      name: build_ffi_generator
    version: ^0.1.0
  build_runner: ^2.0.0
  extra_pedantic: ^1.3.0
  path: ^1.8.0
  test: ^1.17.0
