language: dart
sudo: required
dart:
  - 2.4.1 # TODO: Remove this and bump the lower SDK bound to 2.6.1 once we've upgraded the ecosystem to it
  - stable
dart_task:
  - test: --platform vm
  - test: --platform chrome
  - dartanalyzer
  - dartfmt: true

