name: cloud_firestore
description: Flutter plugin for Cloud Firestore, a cloud-hosted, noSQL database with
  live synchronization and offline support on Android and iOS.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/cloud_firestore
version: 0.9.13+1

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebase.cloudfirestore
    iosPrefix: FLT
    pluginClass: CloudFirestorePlugin

dependencies:
  flutter:
    sdk: flutter
  meta: "^1.0.5"
  collection: "^1.14.3"
  firebase_core: "^0.3.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.2.0 <2.0.0"
