name: webdriver
version: 2.1.2
authors:
  - Marc Fisher II <fisherii@google.com>
  - Matt Staats<staats@google.com>
description: >
  Provides WebDriver bindings for Dart.
  Supports WebDriver JSON interface and W3C spec.
  Requires the use of WebDriver remote server.
homepage: https://github.com/google/webdriver.dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  archive: '>=1.0.0 <3.0.0'
  matcher: ^0.12.3
  path: ^1.3.0
  stack_trace: ^1.3.0
  sync_http: '>=0.1.1 <0.3.0'
dev_dependencies:
  test: '^1.0.0'
