name: synchronized
description: Lock mechanism to prevent concurrent access to asynchronous code.
version: 2.2.0+2
homepage: https://github.com/tekartik/synchronized.dart/tree/master/synchronized

environment:
  sdk: '>=2.8.0 <3.0.0'

dev_dependencies:
  pedantic: '>=1.9.0 <3.0.0'
  pub_semver:
  test: '>=1.5.0'
  build_runner: '>=0.9.2'
  build_test: '>=0.10.3'
  build_web_compilers: '>=1.1.0'
  process_run:
  io:
  yaml:

