name: sqlite3
description: Provides lightweight yet convenient bindings to SQLite by using dart:ffi
version: 0.1.6
homepage: https://github.com/simolus3/sqlite3.dart/tree/master/sqlite3
issue_tracker: https://github.com/simolus3/sqlite3.dart/issues

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  collection: ^1.14.0
  ffi: ^0.1.3
  meta: ^1.1.8

dev_dependencies:
  extra_pedantic: ^1.2.0
  test: ^1.14.4
  build_runner: ^1.10.0
  path: ^1.7.0
  build_ffi_generator:
    git:
      url: https://github.com/simolus3/build_ffi_generator.git
