name: firestore_example
description: Demonstrates how to use the firestore plugin.

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
    path: ../
  firebase_core: "^0.3.2"

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
