name: analyzer_plugin_fork
description: Fork of the analyzer_plugin package with analyzer 0.39 support
version: 0.2.2
homepage: https://github.com/simolus3/analyzer_plugin_fork

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: '^0.39.0'
  charcode: '^1.1.0'
  dart_style: '^1.2.0'
  html: '>=0.13.1 <0.15.0'
  meta: ^1.0.2
  path: '^1.4.1'
  pub_semver: '^1.3.2'
