name: flutter_blurhash
description: Compact representation of a placeholder for an image. Encode a blurry image under 30 caracters for instant display like used by Medium
version: 0.6.0
homepage: https://github.com/fluttercommunity/flutter_blurhash
maintainer: Robert Felker (@Solido)

environment:
  sdk: ">= 2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.3.0
  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

