name: moor
description: Moor is a safe and reactive persistence library for Dart applications
version: 3.3.1
repository: https://github.com/simolus3/moor
homepage: https://moor.simonbinder.eu/
issue_tracker: https://github.com/simolus3/moor/issues

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  convert: ^2.1.1
  collection: ^1.0.0
  synchronized: ^2.1.0
  pedantic: ^1.0.0
  sqlite3: ^0.1.3

dev_dependencies:
  moor_generator: ^3.2.0
  uuid: ^2.0.0
  path: ^1.6.4
  build_runner: '>=1.3.0 <2.0.0'
  test: ^1.9.0
  mockito: ^4.1.0
  rxdart: ^0.24.0 # used to test compatibility with stream queries

#dependency_overrides:
#  moor_generator:
#    path: ../moor_generator
#  sqlparser:
#    path: ../sqlparser