name: cloud_firestore_platform_interface
description: A common platform interface for the cloud_firestore plugin.
version: 5.3.0
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_platform_interface
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_platform_interface

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.5"

dependencies:
  collection: ^1.15.0
  firebase_core: ^1.4.0
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0


dev_dependencies:
  firebase_core_platform_interface: ^4.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
