name: shared_preferences_linux
description: Linux implementation of the shared_preferences plugin
version: 0.0.2+2
homepage: https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences_linux

flutter:
  plugin:
    platforms:
      linux:
        dartPluginClass: SharedPreferencesLinux
        pluginClass: none

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"

dependencies:
  file: ">=5.1.0 <7.0.0"
  flutter:
    sdk: flutter
  meta: ^1.0.4
  path: ^1.6.4
  path_provider_linux: ^0.0.1
  shared_preferences_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
