name: shared_preferences_windows
description: Windows implementation of shared_preferences
repository: https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences_windows
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+shared_preferences%22
version: 2.0.2

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: shared_preferences
    platforms:
      windows:
        dartPluginClass: SharedPreferencesWindows
        pluginClass: none

dependencies:
  flutter:
    sdk: flutter
  file: ^6.0.0
  meta: ^1.3.0
  path: ^1.8.0
  path_provider_platform_interface: ^2.0.0
  path_provider_windows: ^2.0.0
  shared_preferences_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
