language: dart
sudo: false
dart:
  - dev

dart_task:
  - dartanalyzer
  - dartfmt
  - test: --platform vm
  - test: --platform firefox -j 1
  - test: --platform chrome -j 1

matrix:
  allow_failures:
  # Seeing some one-off flakiness - 2018-01-11
  # See https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524
  - dart_task:
      test: --platform chrome -j 1

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
