name: cupertino_icons

description: Default icons asset for Cupertino widgets based on Apple styled icons
homepage: https://github.com/flutter/cupertino_icons
version: 1.0.0

flutter:
  fonts:
    - family: CupertinoIcons
      fonts:
        - asset: assets/CupertinoIcons.ttf

environment:
  sdk: ">=2.0.0 <3.0.0"
