name: xml
version: 4.5.1

description: A lightweight library for parsing, traversing, querying, transforming and building XML documents.
homepage: https://github.com/renggli/dart-xml

environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  collection: ^1.14.0
  convert: ^2.1.0
  meta: ^1.1.0
  petitparser: ^3.0.0
dev_dependencies:
  test: ^1.15.0
  args: ^1.6.0
