name: firebase_auth_web
description: The web implementation of firebase_auth
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth_web
version: 0.3.0+1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAuthWeb
        fileName: firebase_auth_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase: ^7.3.0
  meta: ^1.1.7
  http_parser: ^3.1.3
  intl: ^0.16.1
  firebase_core: ^0.5.0
  firebase_auth_platform_interface: ^2.0.1
  js: ^0.6.1

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  firebase_auth:
    path: ../firebase_auth
  firebase_core_platform_interface: ^2.0.0
  firebase_core_web: ^0.2.0

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"

