name: flutter_facebook_auth_example
description: Demostrates how to use the flutter_facebook_auth plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.2
  google_fonts: ^2.0.0
  provider: ^5.0.0
  permission_handler: ^8.1.1
  flutter_facebook_auth:
    path: ../
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  local_auth: ^1.1.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/android.png
    - assets/ios.png
    - assets/web.png
    - assets/github.png
    - assets/typing.png
