name: recase
version: 4.0.0
description: Changes the case of the input text to the desire case convention.
homepage: https://github.com/techniboogie-dart/recase
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: '^1.16.8'
