name: shared_preferences_windows
description: Windows implementation of shared_preferences
homepage: https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences_windows
version: 0.0.1+1

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: SharedPreferencesWindows
        pluginClass: none

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"

dependencies:
  shared_preferences_platform_interface: ^1.0.0
  flutter:
    sdk: flutter
  ffi: ^0.1.3
  file: ">=5.1.0 <7.0.0"
  meta: ^1.1.7
  path: ^1.6.4
  path_provider_platform_interface: ^1.0.3
  path_provider_windows: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
