name: path_provider_macos
description: macOS implementation of the path_provider plugin
repository: https://github.com/flutter/plugins/tree/master/packages/path_provider/path_provider_macos
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+path_provider%22
version: 2.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: path_provider
    platforms:
      macos:
        pluginClass: PathProviderPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0
