name: xdg_directories
description: A Dart package for reading XDG directory configuration information on Linux.
version: 0.1.0
homepage: https://github.com/flutter/packages/tree/master/packages/animations

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  path: ^1.6.4
  process: ^3.0.12
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
