name: moor_example
description: A todo list application that uses moor to store data
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.2.0
  intl: ^0.16.0
  rxdart: 0.21.0
  moor_flutter: ^3.0.0

dev_dependencies:
  build_runner:
  moor_generator: ^3.2.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  moor_flutter:
    path: ..
  moor_generator:
    path: ../../moor_generator
  moor:
    path: ../../moor
  sqlparser:
    path: ../../sqlparser

flutter:
  uses-material-design: true
