name: cloud_firestore_web
description: The web implementation of cloud_firestore
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_web
version: 0.2.0+1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseFirestoreWeb
        fileName: cloud_firestore_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase: ^7.3.0
  http_parser: ^3.1.3
  meta: ^1.1.7
  firebase_core: ">=0.5.0 <0.6.0"
  cloud_firestore_platform_interface: ">=2.0.1 <2.1.0"
  js: ^0.6.1

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  firebase_core_platform_interface: ">=2.0.0 <2.1.0"
  firebase_core_web: ">=0.2.0 <0.3.0"
  mockito: ^4.1.1

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
