name: path_provider_android
description: Android implementation of the path_provider plugin.
repository: https://github.com/flutter/plugins/tree/master/packages/path_provider/path_provider_android
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+path_provider%22
version: 2.0.9

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: path_provider
    platforms:
      android:
        package: io.flutter.plugins.pathprovider
        pluginClass: PathProviderPlugin

dependencies:
  flutter:
    sdk: flutter
  path_provider_platform_interface: ^2.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.10.0
  plugin_platform_interface: ^2.0.0
  test: ^1.16.0
