name: sqflite_common
homepage: https://github.com/tekartik/sqflite/tree/master/sqflite_common
description: Dart wrapper on SQLite, a self-contained, high-reliability, embedded, SQL database engine.
version: 1.0.2+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  synchronized: '>=2.0.2 <4.0.0'
  path: '>=1.5.1 <3.0.0'
  meta: '>=1.1.8 <3.0.0'

dev_dependencies:
  pedantic: '>=1.4.0 <3.0.0'
  process_run: '>=0.10.7'
  http:
  test:
  test_api:
