name: example
description: A sample application as an example for gsheets.
version: 0.1.0
homepage: https://github.com/a-marenkov/gsheets/tree/master/example

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  gsheets:
    path: ../