name: multicast_dns
description: Dart package for mDNS queries (e.g. Bonjour, Avahi).
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/packages/tree/master/packages/multicast_dns
version: 0.2.2

dependencies:
  meta: ^1.1.6

dev_dependencies:
  test: "^1.3.4"
  mockito: "^4.1.0"

environment:
  sdk: ">=2.1.1-dev.2.0 <3.0.0"
