include: package:effective_dart/analysis_options.yaml
analyzer:
  exclude:
    # Ignore generated files
    - '**/*.g.dart'
    - 'lib/src/generated/*.dart'
linter:
  rules:
    - public_member_api_docs