name: cupertino_icons

description: Default icons asset for Cupertino widgets based on Apple styled icons
homepage: https://github.com/flutter/packages/tree/master/third_party/packages/cupertino_icons
version: 1.0.3

flutter:
  fonts:
    - family: CupertinoIcons
      fonts:
        - asset: assets/CupertinoIcons.ttf

environment:
  sdk: ">=2.12.0 <3.0.0"
