name: flutter_facebook_auth_web
description: web support for flutter_facebook_auth
version: 2.6.0+2
homepage: https://github.com/darwin-morocho/flutter-facebook-auth/tree/master/facebook_auth_web

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  flutter_facebook_auth_platform_interface: ^2.7.0
  # flutter_facebook_auth_platform_interface:
  #   path: ../facebook_auth_platform_interface
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterFacebookAuthPlugin
        fileName: flutter_facebook_auth_web.dart
