name: checked_yaml
version: 1.0.4
description: >-
  Generate more helpful exceptions when decoding YAML documents using
  package:json_serializable and package:yaml.
repository: https://github.com/google/json_serializable.dart
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  json_annotation: '>=2.2.0 <5.0.0'
  source_span: ^1.0.0
  yaml: '>=2.1.13 <4.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  build_verify: ^1.1.0
  json_serializable: ^3.0.0
  path: ^1.0.0
  test: ^1.6.0
  test_process: ^1.0.1
