name: syncfusion_flutter_core
description: Syncfusion Flutter Core is a dependent package for all the Syncfusion Flutter widgets. 
version: 19.3.47
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_core

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vector_math: ">=2.1.0 <=3.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ">=1.9.0 <2.0.0"

flutter:
