// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'asset_manifest_test.dart' as asset_manifest_test;
import 'generated_font_methods_test.dart' as generated_font_methods_test;
import 'google_fonts_family_with_variant_test.dart' as google_fonts_family_with_variant_test;
import 'google_fonts_variant_test.dart' as google_fonts_variant_test;
import 'load_font_if_necessary_test.dart' as load_font_if_necessary_test;
import 'load_font_if_necessary_with_local_fonts_test.dart' as load_font_if_necessary_with_local_fonts_test;

void main() {
  load_font_if_necessary_test.main();
  google_fonts_variant_test.main();
  asset_manifest_test.main();
  load_font_if_necessary_with_local_fonts_test.main();
  google_fonts_family_with_variant_test.main();
  generated_font_methods_test.main();
}
