name: firebase_dynamic_links_example
description: Demonstrates how to use the firebase_dynamic_links plugin.

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  firebase_core:
    path: ../../firebase_core/firebase_core
  firebase_dynamic_links:
    path: ../
  flutter:
    sdk: flutter
  url_launcher: ^6.0.2

dependency_overrides:
  firebase_core:
    path: ../../firebase_core/firebase_core
  firebase_core_platform_interface:
    path: ../../firebase_core/firebase_core_platform_interface
  firebase_core_web:
    path: ../../firebase_core/firebase_core_web

dev_dependencies:
  drive: 0.1.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
