analyzer:
  strong-mode:
    implicit-casts: false
linter:
  rules:
    - annotate_overrides
    - avoid_return_types_on_setters
    - empty_constructor_bodies
    - empty_statements
    #- prefer_single_quotes
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - valid_regexps
