name: analyzer_plugin_fork
description: Fork of the analyzer_plugin package with analyzer 0.40 support
version: 0.3.0
homepage: https://github.com/simolus3/analyzer_plugin_fork

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  analyzer: '^0.40.4'
  charcode: '^1.1.0'
  dart_style: '^1.2.0'
  pub_semver: '^1.3.2'

dev_dependencies:
  html: '>=0.13.1 <0.15.0'
  path: '^1.4.1'
  test_reflective_loader: ^0.1.8
  test: ^1.0.0
