name: search_page
description: Fast and easy way to build a custom search experience in you app
version: 1.3.0
homepage: https://github.com/jesusrp98/search_page

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
