name: nested
description: A Flutter Widget which helps nest multiple widgets without needing to manually nest them.
version: 0.0.4
author: Remi Rousselet <darky12s@gmail.com>
homepage: https://github.com/rrousselGit/nested

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter