name: petitparser
version: 4.4.0

homepage: https://github.com/petitparser/dart-petitparser
description: A dynamic parser framework to build efficient grammars and parsers
  quickly.

environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  meta: ^1.7.0
dev_dependencies:
  test: ^1.17.0
  lints: ^1.0.0
