name: flutter_template_images
description: Image files for use in flutter_tools templates.
version: 1.0.1
homepage: https://github.com/flutter/packages/tree/master/packages/flutter_template_images

environment:
  sdk: ">=2.1.0 <3.0.0"
