name: connectivity_plus_web_example
description: Example web app for the connectivity plugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.26.0-0"

dependencies:
  connectivity_plus_web:
    path: ../../connectivity_plus_web
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.0

dependency_overrides:
  args: ^2.0.0
  convert: ^3.0.0
  crypto: ^3.0.0
