name: path_drawing
version: 0.4.1+1
description: >
  A flutter library to help with (Canvas) Path creation and manipulation
author: Dan Field <dfield@gmail.com>
homepage: https://github.com/dnfield/flutter_path_drawing

dependencies:
  vector_math: ">=2.0.6 <3.0.0"
  meta: ">=1.1.2 <2.0.0"
  path_parsing: ^0.1.4
  flutter:
    sdk: flutter

dev_dependencies:
  path: ^1.5.1
  test: "^1.3.4"
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # There's no need to include these as we don't use them.
  # This fixes an issue when our plugin is imported into a project that also
  # uses no material icons.
  uses-material-design: false

environment:
  sdk: ">=1.19.0 <3.0.0"
  flutter: ">=0.3.6 <2.0.0"
