name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_auth:
    path: ../
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_dynamic_links:
    path: ../../../firebase_dynamic_links
  flutter:
    sdk: flutter
  flutter_signin_button: ^1.0.0
  google_sign_in: ^5.0.0-nullsafety

dependency_overrides:
  firebase_auth:
    path: ../
  firebase_auth_platform_interface:
    path: ../../firebase_auth_platform_interface
  firebase_auth_web:
    path: ../../firebase_auth_web
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_core_platform_interface:
    path: ../../../firebase_core/firebase_core_platform_interface
  firebase_core_web:
    path: ../../../firebase_core/firebase_core_web
  firebase_dynamic_links:
    path: ../../../firebase_dynamic_links

dev_dependencies:
  drive: 0.1.0
  flutter_driver:
    sdk: flutter
  http: ^0.13.0
  test: any

flutter:
  uses-material-design: true
