name: google_api_availability_example
description: Demonstrates how to use the google_api_availability plugin.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  e2e: ^0.4.0
  flutter_driver:
    sdk: flutter

  google_api_availability:
    path: ../

flutter:
  uses-material-design: true